### ISSUE TITLE
Cannot use 'in' operator to search for 'start' in undefined

### ISSUE THREAD

**Issue by easoncxz** [JSMonk/hegel#308]
I don't have a minimal reproduction yet, but it seems to be related to the interpretation of `.hegelrc` file.

If in `.hegelrc` I put:

```yaml
environment: browser
include:
  - ./src/**/*.js
exclude:
  - ./static/**
  - ./es5/**
  - ./node_modules/**
types:
  - ./@types
  - ./node_modules/@types
```

and run `npx hegel`, I get:

```
[0] $ npx hegel
Cannot use 'in' operator to search for 'start' in undefined

[1] $
```

However if I add a bogus entry to `include:` at the start, like `bogus.js` here:

```yaml
environment: browser
include:
  - bogus.js
  - ./src/**/*.js
exclude:
  - ./static/**
  - ./es5/**
  - ./node_modules/**
types:
  - ./@types
  - ./node_modules/@types
```

Then type-checking is fine:

```
[0] $ npx hegel
No errors!

[0] $
```

I found #102, but not sure how related it is.
